# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e49f9a8dcaacf65dcdaf26893d7f4494a52d3dd91aac70eb8d5f74a48a28d347d1d93b5c3ec1483f37a9db78afdd0125951e1966ac091e1a422abd09ed925ad

test:
  secret_key_base: 95f091c323254fa70fc1bc88db098546f5079fbc8d37c0caa54cc045aa18055c32fcbbf8296f297d6e4276de82699a8f0db9ccf5d8e58bad0ce59c271b188723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
